### ISSUE TITLE
stubby sending queries in cleartext?

### ISSUE THREAD

**Issue by tykling** [getdnsapi/getdns#344] opened 2017-10-16 22:19 UTC
1. installed getdns 1.1.0 in debian stretch
2. added the following config and started stubby:
```
{ 
  "resolution_type": GETDNS_RESOLUTION_STUB,
  "dns_transport_list": [ GETDNS_TRANSPORT_TLS ],
  "tls_authentication": GETDNS_AUTHENTICATION_REQUIRED,
  "tls_query_padding_blocksize": 256,
  "edns_client_subnet_private": 1,
  "listen_addresses": [ 0.0.0.0, :: ],
  "idle_timeout": 10000,
  "round_robin_upstreams": 1,
  "upstream_recursive_servers":
  [
    {
      "address_data": 89.233.43.71,
      "tls_auth_name": "unicast.censurfridns.dk",
      "tls_pubkey_pinset":
      [
        {
          "digest": "sha256",
          "value": wikE3jYAA6jQmXYTr/rbHeEPmC78dQwZbQp6WdrseEs=
        }
      ]
    },
    {
      "address_data": 2a01:3a0:53:53::,
      "tls_auth_name": "unicast.censurfridns.dk",
      "tls_pubkey_pinset":
      [
        {
          "digest": "sha256",
          "value": wikE3jYAA6jQmXYTr/rbHeEPmC78dQwZbQp6WdrseEs=
        }
      ]
    }
  ]
}
```
3. started tcpdump on the upstream interface
4. did a few dig's and saw that the queries are going to the resolver configured in /etc/resolv.conf in clear text rather than going to the upstreams in stubby.conf over TLS.

What am I doing wrong? Thanks!

**Comment by saradickinson** [comment] 2017-10-17 11:16
For reference - installation instruction for linux:
https://dnsprivacy.org/wiki/pages/viewpage.action?pageId=3145786
You may want to just listen specifically on local host:
```"listen_addresses": [ 127.0.0.1, 0::1 ],```

So if you do 'dig @127.0.0.1 getdnsapi.net' with stubby running and see the query go out in clear text it sounds like stubby isn't finding the config file and is defaulting to Opportunistic with system resolvers. But you should see an error reported when you start stubby in this case.... 
So try running 
```stubby -i -C <your_config_file>```
as this will report back the exact configuration stubby is actually using.

**Comment by wtoorop** [comment] 2017-11-23 10:43
Thomas, I'm closing the issue since I cannot reproduce and I think it is not related to Stubby.
If you disagree, please provide more background information and I'll reopen.

**Closed by wtoorop** 2017-11-23 10:43 UTC
