### ISSUE TITLE
getdns is killed

### ISSUE THREAD

**Issue by Seagulls** [getdnsapi/getdns#409] opened 2018-11-09 09:40 UTC
I've installed getdns v1.4.2 on my DD-WRT using opkg.

I can run getdns_query -h and it outputs the help menu however whenever I try to run a query it immediately is killed.

I can't figure out what's wrong, here is the strace, any information would be appreciated.

```
[root@DD-WRT /] strace getdns_query
execve("/opt/sbin/getdns_query", ["getdns_query"], 0x7ff759d0 /* 26 vars */) = 0
brk(NULL)                               = 0x41b000
mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x77a09000
uname({sysname="Linux", nodename="DD-WRT", ...}) = 0
access("/opt/etc/ld.so.preload", R_OK)  = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/tls/libgetdns.so.10", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/opt/lib/tls", {st_mode=S_IFDIR|0755, st_size=1024, ...}) = 0
openat(AT_FDCWD, "/opt/lib/libgetdns.so.10", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0`\206\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=466020, ...}) = 0
mmap2(NULL, 505184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7795c000
mprotect(0x779c3000, 61440, PROT_NONE)  = 0
mmap2(0x779d2000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x66000) = 0x779d2000
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0\220\307\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=358476, ...}) = 0
mmap2(NULL, 422812, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x778f4000
mprotect(0x77948000, 61440, PROT_NONE)  = 0
mmap2(0x77957000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x53000) = 0x77957000
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0\0\221\3\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=1692352, ...}) = 0
mmap2(NULL, 1763652, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x77744000
mprotect(0x778d0000, 61440, PROT_NONE)  = 0
mmap2(0x778df000, 73728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18b000) = 0x778df000
mmap2(0x778f1000, 6468, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x778f1000
mprotect(0x7f977000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) = 0
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0 O\0\0004\0\0\0"..., 512) = 512
_llseek(3, 768, [768], SEEK_SET)        = 0
read(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\2\0\0\0\0\0\0\0", 32) = 32
fstat64(3, {st_mode=S_IFREG|0755, st_size=118872, ...}) = 0
mmap2(NULL, 181296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x77716000
mprotect(0x77730000, 61440, PROT_NONE)  = 0
mmap2(0x7773f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7773f000
mmap2(0x77741000, 5168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x77741000
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0\340(\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=95288, ...}) = 0
mmap2(NULL, 153760, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x776f0000
mprotect(0x77706000, 61440, PROT_NONE)  = 0
mmap2(0x77715000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x77715000
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0\204\235\1\0004\0\0\0"..., 512) = 512
_llseek(3, 792, [792], SEEK_SET)        = 0
read(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\2\0\0\0\0\0\0\0", 32) = 32
fstat64(3, {st_mode=S_IFREG|0755, st_size=1652528, ...}) = 0
mmap2(NULL, 1626288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x77562000
mprotect(0x776d7000, 61440, PROT_NONE)  = 0
mmap2(0x776e6000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x174000) = 0x776e6000
mmap2(0x776ed000, 8368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x776ed000
close(3)                                = 0
openat(AT_FDCWD, "/opt/lib/tls/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0`\v\0\0004\0\0\0"..., 512) = 512
_llseek(3, 680, [680], SEEK_SET)        = 0
read(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\2\0\0\0\0\0\0\0", 32) = 32
fstat64(3, {st_mode=S_IFREG|0755, st_size=10664, ...}) = 0
mmap2(NULL, 73952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7754e000
mprotect(0x77550000, 61440, PROT_NONE)  = 0
mmap2(0x7755f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7755f000
close(3)                                = 0
mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x77a07000
set_thread_area(0x77a0ed70)             = 0
mprotect(0x776e6000, 16384, PROT_READ)  = 0
mprotect(0x7755f000, 4096, PROT_READ)   = 0
mprotect(0x7773f000, 4096, PROT_READ)   = 0
mprotect(0x77a0b000, 4096, PROT_READ)   = 0
set_tid_address(0x77a07948)             = 28367
set_robust_list(0x77a07950, 12)         = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7771a8d8, sa_mask=[], sa_flags=SA_SIGINFO}, NULL, 16) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7771a9e4, sa_mask=[], sa_flags=SA_RESTART|SA_SIGINFO}, NULL, 16) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 16) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=2147483647}) = 0
brk(NULL)                               = 0x41b000
brk(0x43c000)                           = 0x43c000
stat("/opt/etc/unbound/getdns-root.key", {st_mode=S_IFREG|0644, st_size=1252, ...}) = 0
openat(AT_FDCWD, "/opt/etc/unbound/getdns-root.key", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=1252, ...}) = 0
read(3, "; autotrust trust anchor file\n;;"..., 1024) = 1024
read(3, "J8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQ"..., 1024) = 228
read(3, "", 1024)                       = 0
close(3)                                = 0
futex(0x775600b4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/opt/lib/tls/libz.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/lib/libz.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\10\0\1\0\0\0\360\26\0\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0644, st_size=90356, ...}) = 0
mmap2(NULL, 150384, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x77528000
mprotect(0x7753d000, 61440, PROT_NONE)  = 0
mmap2(0x7754c000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7754c000
close(3)                                = 0
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=23, ...}) = 0
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=23, ...}) = 0
read(3, "nameserver 192.168.1.1\n", 4096) = 23
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=23, ...}) = 0
read(3, "nameserver 192.168.1.1\n", 4096) = 23
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/hosts", O_RDONLY) = 3
stat("/etc/hosts", {st_mode=S_IFREG|0644, st_size=106, ...}) = 0
fstat64(3, {st_mode=S_IFREG|0644, st_size=106, ...}) = 0
read(3, "127.0.0.1\tlocalhost\n192.168.1.1\t"..., 4096) = 106
read(3, "", 4096)                       = 0
close(3)                                = 0
gettimeofday({tv_sec=1541755996, tv_usec=986216}, NULL) = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3
fcntl64(3, F_GETFL)                     = 0x2 (flags O_RDWR)
fcntl64(3, F_SETFL, O_RDWR|O_NONBLOCK)  = 0
gettimeofday({tv_sec=1541755996, tv_usec=987937}, NULL) = 0
gettimeofday({tv_sec=1541755996, tv_usec=991367}, NULL) = 0
poll([{fd=3, events=POLLOUT}], 1, 4996) = 1 ([{fd=3, revents=POLLOUT}])
gettimeofday({tv_sec=1541755996, tv_usec=995370}, NULL) = 0
gettimeofday({tv_sec=1541755996, tv_usec=997257}, NULL) = 0
getpid()                                = 28367
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 16) = 0
getpid()                                = 28367
gettid()                                = 28367
tgkill(28367, 28367, SIGKILL)           = ?
+++ killed by SIGKILL +++
Killed
```

**Comment by hanvinke** [comment] 2018-11-09 11:08
A pity it doesn't work!

One question:
Did you use opkg to install libgcc and libcc prior to installing getdns, or
afterwards?
(Because I see some errors in the log)



Op vr 9 nov. 2018 10:40 schreef Seagulls <notifications@github.com:

**Comment by Seagulls** [comment] 2018-11-09 12:10
Hey, thank you for the response.

I installed libgcc a few months ago using opkg: libgcc - 7.3.0-8

I don't see "libcc" as a package available, but I have libc - 2.27-8

Regards.

**Comment by hanvinke** [comment] 2018-11-09 16:55
Thanks for the info. 

Did you install stubby also?
opkg install stubby getdns 

(because getdns only provides the library)

**Comment by Seagulls** [comment] 2018-11-09 17:17
Hey, yes I have stubby installed.

I run stubby -l with this output:

```
[root@DD-WRT ~] stubby -l
[17:14:20.279389] STUBBY: Read config from file /opt/etc/stubby/stubby.yml
[17:14:20.286330] STUBBY: DNSSEC Validation is OFF
[17:14:20.288120] STUBBY: Transport list is:
[17:14:20.289799] STUBBY:   - TLS
[17:14:20.291733] STUBBY: Privacy Usage Profile is Strict (Authentication required)
[17:14:20.293351] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)
[17:14:20.295462] STUBBY: Starting DAEMON....
```
I then ran: 
`
dig @127.0.0.1 -p 5453 www.google.com`

And stubby produced:

```
[17:14:32.184724] STUBBY: 145.100.185.15 : Conn opened: TLS - Strict Profile
[17:14:32.366310] STUBBY: 145.100.185.15 : Verify passed : TLS
Killed
```

**Comment by wtoorop** [comment] 2018-11-27 15:31
Thanks for the strace, but a backtrace from gdb would be more helpful.
Is it possible for you to compile with debugging symbols and gdb a getdns_query?

**Comment by Seagulls** [comment] 2018-11-28 09:10
> 
> 
> Thanks for the strace, but a backtrace from gdb would be more helpful.
> Is it possible for you to compile with debugging symbols and gdb a getdns_query?

I'll look into it at the weekend, see if there's a docker container for cross compiling for DD-WRT.

**Comment by wtoorop** [comment] 2018-11-29 14:06
Issue getdnsapi/stubby#140 might be the same as what you have...

**Comment by Seagulls** [comment] 2018-12-01 17:55
> 
> 
> Issue [getdnsapi/stubby#140](https://github.com/getdnsapi/stubby/issues/140) might be the same as what you have...

I've compiled getdns from source on my router and used the patch mentioned in that topic and it appears to be working now 👍

**Comment by hanvinke** [comment] 2018-12-10 21:19
Are these problems maybe due to the kernel not building up enough entropy?
This was my initial thought, because these routers are static devices, without input from a mouse or keyboard for instance. I don't think the devices used for DD-WRT are having the luxury of a True Random Number Generator (hardware).

Is there a standard way getdns/stubby handles these exceptions? Or is "+++ killed by SIGKILL +++" simply an error which is caused by insufficient entropy?

**Comment by wtoorop** [comment] 2018-12-31 15:20
Hello Han, the arc4random code is copied from OpenBSD I believe... it had a statement killing the running process when it could not get enough entropy (probably for security reasons). The updated version falls back to reading from `/dev/urandom` and doesn't kill itself anymore, so this situation should not occur anymore... I suspect that we're a bit less secure on embedded devices after this update, but alas... better than not resolving at all.

**Closed by wtoorop** 2018-12-31 15:20 UTC
